modLoader="javafml" #mandatory
loaderVersion="[32,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Nomit333/FriendsOres/issues"
[[mods]]
modId="friendsores"
version="1.16.1-1.0.2"
displayName="Friends Ores"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
# logoFile="examplemod.png"
credits="Thanks to friends and more for the Ideas"
authors="Timon Andreas Wegner"
description='''
'''
[[dependencies.friendsores]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.friendsores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
